apiVersion: apps/v1
kind: Deployment
metadata:
  name: filemanager
  labels:
    app: filemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filemanager
  template:
    metadata:
      labels:
        app: filemanager
    spec:
      containers:
        - name: filemanager
          image: jaime197/filemanager:v4
          ports:
            - containerPort: 32443
---
apiVersion: v1
kind: Service
metadata:
  name: filemanager-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: filemanager
  ports:
    - protocol: TCP
      port: 32443
      targetPort: 32443
      nodePort: 32443
