apiVersion: apps/v1
kind: Deployment
metadata:
  name: multmatrix
  labels:
    app: multmatrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multmatrix
  template:
    metadata:
      labels:
        app: multmatrix
    spec:
      containers:
        - name: multmatrix
          image: jaime197/multmatrix:v1
          ports:
            - containerPort: 32444
---
apiVersion: v1
kind: Service
metadata:
  name: multmatrix-service
spec:
  type: NodePort
  selector:
    app: multmatrix
  ports:
    - port: 32444
      targetPort: 32444
      nodePort: 32444
  externalTrafficPolicy: Cluster
